name: NestJs CI 

on: 
  push: 
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: ${{ secrets.POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_NAME: ${{ secrets.POSTGRES_DB }}

    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: pnpm setup
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm Dependencies globally 
        run: npm install -g pnpm

      - name: Install node modules
        run: pnpm install

      - name: Check if secrets are coming
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
          echo "DATABASE_URL secret is **NOT set**!"
          exit 1
          else
            echo "DATABASE_URL secret is set"
          fi

          if [ -z "${{ secrets.POSTGRES_USER }}" ]; then
            echo "POSTGRES_USER secret is **NOT set**!"
            exit 1
          else
            echo "POSTGRES_USER secret is set"
          fi

          if [ -z "${{ secrets.POSTGRES_PASSWORD }}" ]; then
            echo "POSTGRES_PASSWORD secret is **NOT set**!"
            exit 1
          else
            echo "POSTGRES_PASSWORD secret is set"
          fi

          if [ -z "${{ secrets.POSTGRES_DB }}" ]; then
            echo "POSTGRES_DB secret is **NOT set**!"
            exit 1
          else
            echo "POSTGRES_DB secret is set"
          fi  

      - name: Start Docker services
        run: docker compose up -d

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Postgres ready" && exit 0
            echo "Waiting for Postgres..."
            sleep 3
          done
          exit 1

      - name: Run migrations for prisma
        run: pnpm prisma migrate deploy

      - name: Build Project
        run: pnpm run build

      - name: Run Tests
        run: pnpm test   

      - name: Stop containers
        if: always()
        run: docker compose down  
