name: NestJs CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: uat-test-case

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_HOST: localhost
      DB_PORT: 5432
      # DB_USER: ${{ secrets.POSTGRES_USER }}
      # DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      # DB_NAME: ${{ secrets.POSTGRES_DB }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Prisma migrations
        run: pnpm prisma migrate deploy

      - name: Build project
        run: pnpm run build

      - name: Run tests
        run: pnpm test